import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path, { join } from 'node:path'

import sharp from 'sharp'

const __dirname = path.dirname(new URL(import.meta.url).pathname)

// Create rounded corners mask
function createRoundedCornersMask(size: number, cornerRadius: number) {
  const r = cornerRadius
  return `
    <svg width="${size}" height="${size}" xmlns="http://www.w3.org/2000/svg">
      <rect x="0" y="0" width="${size}" height="${size}" rx="${r}" ry="${r}" fill="white"/>
    </svg>
  `
}

// Add rounded corners to the image
async function addRoundedCorners(
  imageBuffer: Buffer,
  size: number,
): Promise<Buffer> {
  // Calculate corner radius, about 12% of the size
  const cornerRadius = Math.round(size * 0.12)

  const maskSvg = createRoundedCornersMask(size, cornerRadius)
  const maskBuffer = Buffer.from(maskSvg)

  return sharp(imageBuffer)
    .composite([
      {
        input: maskBuffer,
        blend: 'dest-in',
      },
    ])
    .png()
    .toBuffer()
}

// Generate favicons of different sizes
export async function generateFavicons() {
  const logoPath = join(__dirname, '../logo.jpg')
  const outputDir = join(process.cwd(), 'public')

  // Check if the logo file exists
  if (!existsSync(logoPath)) {
    throw new Error('Logo file not found: logo.jpg')
  }

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true })
  }

  const sizes = [
    { size: 16, name: 'favicon-16x16.png' },
    { size: 32, name: 'favicon-32x32.png' },
    { size: 48, name: 'favicon-48x48.png' },
    { size: 180, name: 'apple-touch-icon.png' },
    { size: 192, name: 'android-chrome-192x192.png' },
    { size: 512, name: 'android-chrome-512x512.png' },
  ]

  try {
    // Read the original logo image
    const logoBuffer = await sharp(logoPath).jpeg({ quality: 100 }).toBuffer()

    // Generate PNG files of various sizes
    for (const { size, name } of sizes) {
      const resizedBuffer = await sharp(logoBuffer)
        .resize(size, size, {
          fit: 'cover',
          position: 'center',
        })
        .png({
          quality: 100,
          compressionLevel: 6,
        })
        .toBuffer()

      // Add rounded corners effect
      const roundedBuffer = await addRoundedCorners(resizedBuffer, size)

      const outputPath = join(outputDir, name)
      writeFileSync(outputPath, roundedBuffer)
      console.info(`✅ Generated favicon: ${name} (${size}x${size})`)
    }

    // Generate the main favicon.ico (using 32x32)
    const faviconResizedBuffer = await sharp(logoBuffer)
      .resize(32, 32, {
        fit: 'cover',
        position: 'center',
      })
      .png({
        quality: 100,
        compressionLevel: 6,
      })
      .toBuffer()

    // Add rounded corners to favicon.ico
    const faviconBuffer = await addRoundedCorners(faviconResizedBuffer, 32)

    const faviconPath = join(outputDir, 'favicon.ico')
    writeFileSync(faviconPath, faviconBuffer)
    console.info(`✅ Generated main favicon: favicon.ico`)

    // The PWA manifest is generated by vite-plugin-pwa, so no duplicate files are generated here

    console.info(
      `🎨 All favicons generated successfully from logo.jpg with rounded corners!`,
    )
  } catch (error) {
    console.error('❌ Error generating favicons:', error)
    throw error
  }
}

// If this script is run directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateFavicons().catch(console.error)
}
